import Head from 'next/head'
import { Header } from 'src/components'

export default function Home() {
  return (
    <>
      <div className="flex min-h-screen flex-col items-center justify-center py-2" ></div>
      <Head>
        <title>Movie - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  )
}
