import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Header, Hero, Row } from 'src/components'
import { IMovie } from 'src/components/interfaces/app.interface';
import { API_REQUEST } from 'src/services/api.service';

export default function Home({trending, topRated}: HomeProps): JSX.Element {
  console.log(topRated);
  
  return (
    <>
      <div className="relativ h-[200vh]" >
        <Head>
          <title>Movie - HOME</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.svg" />
        </Head>
        <Header />
        <main className='relative pb-24 lg:space-y-24 '>
          <div className='pl-4 lg:pl-16'>
            <Hero trending={trending}/>
          </div>
          <section>
            <Row title='Top Rated' movies={topRated}/>
            <Row title='TV Shows' movies={topRated} />
          </section>
        </main>
      </div>
    </>
  )
}



export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REQUEST.trending).then(res => res.json());
  const topRated = await fetch(API_REQUEST.top_rated).then(res => res.json());

  return {
    props: {
      trending: trending.results,
      topRated: topRated.results
    },
  };
};

interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
}